apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: humanglue-ingress
  namespace: humanglue
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
    - hosts:
        - hmnglue.com
        - www.hmnglue.com
      secretName: humanglue-tls
  rules:
    - host: hmnglue.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: humanglue-web
                port:
                  number: 80
    - host: www.hmnglue.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: humanglue-web
                port:
                  number: 80
