apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: humanglue

resources:
  - namespace.yaml
  - discord-bot-deployment.yaml
  - agent-deployment.yaml
  - nextjs-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: humanglue
  app.kubernetes.io/managed-by: kustomize
